language: r

cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
